---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfidentity/uaa-key-rotator-sqlserver
inputs:
  - name: uaa
  - name: uaa-key-rotator

run:
  path: uaa-key-rotator/ci/tasks/run-unit-tests-sqlserver/task.sh

params:
  DB_SCHEME: sqlserver
  DB_NAME: uaa
  DB_USERNAME: root
  DB_PASSWORD: changemeCHANGEME1234!
  DB_HOSTNAME: localhost
  DB_PORT: 1433