---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/uaa-postgresql
inputs:
  - name: uaa
  - name: uaa-key-rotator

run:
  path: uaa-key-rotator/ci/tasks/run-unit-tests/task.sh
